/**
 * @file PresetMeta.h
 * @brief Measured metadata for the built-in presets: a 2-D map position, a few
 *        perceptual descriptors and tags.
 *
 * Generated by Tools/preset_map.py from renders of every
 * preset (never edited by hand: Core/src/PresetMeta.cpp). The browser filters and sorts on
 * this, the map draws it, and PresetMap.h blends between neighbours on the map.
 *
 * Two views are declared here. The built-in table alone (builtinPresetMeta and friends) is the
 * generated file; the public view (presetMeta and friends, defined in PresetPacks.cpp) is that
 * table followed by the metadata of every loaded pack, indexed exactly as numPresets() counts,
 * so a caller never needs to know where the built-ins end. The clusters and the phrase table
 * (PresetClusters.cpp) are generated too.
 */
#pragma once
#include <cstdint>

namespace ambient {

/**
 * @brief The tag bits a preset may carry (PresetMeta::tags), set by the measurement and by the
 *        preset's own settings; presetTagName() gives each bit's name.
 */
enum PresetTag : uint32_t {
    TagDark = 1u << 0, TagBright = 1u << 1, TagCalm = 1u << 2, TagMoving = 1u << 3,   ///< Dark and Bright from the spectral centroid; Calm and Moving from the spectral flux
    TagTonal = 1u << 4, TagNoisy = 1u << 5, TagWide = 1u << 6, TagBass = 1u << 7,   ///< Tonal and Noisy from the flatness; Wide from the stereo correlation; Bass from the energy below 150 Hz
    TagDense = 1u << 8, TagSparse = 1u << 9, TagKeys = 1u << 10, TagGenerative = 1u << 11,   ///< Dense and Sparse from the voice count; Keys means played rather than self-playing; Generative the brain is on
    TagCosmos = 1u << 12, TagFeedback = 1u << 13, TagSources = 1u << 14, TagJustIntonation = 1u << 15,   ///< what the settings switch on: the Cosmos send, the feedback loop, extra source slots, a just scale
    TagSub = 1u << 16, TagStack = 1u << 17, TagAir = 1u << 18,   ///< the Foundation sub, strands at pure ratios (Stack), the Air layer
    /// What a drone is: whether it goes anywhere, whether its partials grind, and how far away it
    /// stands. Added in 1.11.0 with the descriptors behind them.
    TagStill = 1u << 19, TagEvolving = 1u << 20, TagSmooth = 1u << 21, TagRough = 1u << 22,   ///< Still and Evolving from evolve; Smooth and Rough from rough
    TagNear = 1u << 23, TagFar = 1u << 24,   ///< Near and Far from wet
};
constexpr int kNumPresetTags = 25;   ///< how many bits of PresetTag are defined (0 .. kNumPresetTags-1 name a tag)

/**
 * @brief What was measured about one preset: where it sits on the map, how it sounds by nine
 *        ranked descriptors, and what it is filed under.
 *
 * Every descriptor is a rank over the library (0 = the least of all presets, 1 = the most), so the
 * browser's sliders and the map's axes mean the same thing for a built-in and a pack preset.
 */
struct PresetMeta {
    float x,   ///< @brief map position, 0..1: across
          y;   ///< map position, 0..1
    float bright;               ///< 0..1 rank of the spectral centroid
    float motion;               ///< 0..1 rank of the spectral flux
    float width;                ///< 0..1 rank of stereo width (1 - |correlation|)
    float noisy;                ///< 0..1 rank of spectral flatness
    float bass;                 ///< 0..1 rank of the energy below 150 Hz
    float density;              ///< 0..1 rank of the mean voice count
    int   family;               ///< index into familyName()
    uint32_t tags;              ///< PresetTag bits
    float loudDb;               ///< measured RMS of a 12 s render, dBFS; 0 = never measured
    /// Three descriptors that say what a DRONE is like rather than what a note is like. Flux and
    /// centroid describe a moment; these describe a minute, a spectrum's friction and a distance.
    float evolve;               ///< 0..1 rank: how far the sound travels over the render
    float rough;                ///< 0..1 rank: Plomp-Levelt roughness of its own spectrum
    float wet;                  ///< 0..1 rank: what comes back from the far planes, against the near
    /// What a model that listened to the render says it sounds like: two indices into the phrase
    /// table, best first, or -1. CLAP scores a written vocabulary against every preset (see
    /// Tools/library/clap_embed.py); it cannot invent a phrase, only choose one, which is what
    /// makes the line honest -- a person wrote the words, a measurement picked them.
    short phrase[2];            ///< indices into presetPhrase(), best first; -1 for none
    /// The group this preset was put in when the whole library was laid out, or -1. It is stored
    /// rather than recomputed because the grouping sees more than the nine numbers above -- the
    /// fingerprint and the learned embedding have a say -- so a nearest-centroid guess would put
    /// some presets in a different group than the map draws them in.
    short cluster;              ///< the stored group (see presetClusterOf), or -1
};
constexpr int kNumMapDescriptors = 9;   ///< bright motion width noisy bass density evolve rough wet

/**
 * @brief The measured groups: presets that sound alike, found by k-means over those nine descriptors
 *        across the whole library.
 *
 * The centroids are generated; a preset's group is the nearest one,
 * worked out here rather than stored per preset, so a built-in and a pack preset are grouped by
 * the same yardstick even though two different tools measured them.
 *
 * @return how many clusters the generated table holds (0 for the stub)
 */
int               numPresetClusters();
/**
 * @brief The name of a cluster, for the browser.
 * @param cluster  0 .. numPresetClusters()-1
 * @return         the name, or "" when out of range
 */
const char*       presetClusterName(int cluster);
/**
 * @brief The centroid of a cluster in descriptor space.
 * @param cluster  0 .. numPresetClusters()-1
 * @return         kNumMapDescriptors values in the order of kNumMapDescriptors' comment, or nullptr when out of range
 */
const float*      presetClusterCentre(int cluster);
/**
 * @brief The stored group, else the nearest centroid, else -1.
 *
 * The one unnamed argument is the preset's metadata: its cluster field is returned when it names
 * a valid group, otherwise the centroid nearest to its nine descriptors is found.
 *
 * @return the cluster index, or -1 when there are no clusters
 */
int               presetClusterOf(const PresetMeta&);

/**
 * @brief The vocabulary CLAP chose from, and one preset's phrases.
 * @return how many phrases the generated table holds (0 for the stub)
 */
int               numPresetPhrases();
/**
 * @brief One phrase of the vocabulary, as PresetMeta::phrase indexes it.
 * @param index  0 .. numPresetPhrases()-1
 * @return       "" when out of range or not generated
 */
const char*       presetPhrase(int index);

/**
 * @brief Public view: the built-in table followed by the loaded packs (see Presets.h).
 * @return equals numPresets() once generated, 0 for the stub
 */
int               numPresetMeta();
/**
 * @brief The metadata of one preset, built-in or pack, indexed as numPresets() counts.
 * @param index  0 .. numPresetMeta()-1
 * @return       the entry, or a neutral one (everything 0.5, no tags, no cluster) when out of range
 */
const PresetMeta& presetMeta(int index);
/** @return built-in families plus one per pack */
int               numPresetFamilies();
/**
 * @brief The name of a family, for the browser's list.
 * @param family  0 .. numPresetFamilies()-1: a built-in family, then the packs in load order
 * @return        the built-in family's name or the pack's name, "" when out of range
 */
const char*       presetFamilyName(int family);
/**
 * @brief The name of a tag bit.
 * @param bit  0 .. kNumPresetTags-1
 * @return     the name ("Dark", "Bright", ...), or "" when out of range
 */
const char*       presetTagName(int bit);

/**
 * @brief The generated table alone (Core/src/PresetMeta.cpp, written by Tools/preset_map.py).
 * @return how many built-in presets were measured
 */
int               builtinPresetMetaCount();
/**
 * @brief One built-in preset's metadata.
 * @param index  0 .. builtinPresetMetaCount()-1
 * @return       the entry, or a neutral one when out of range
 */
const PresetMeta& builtinPresetMeta(int index);
/** @return how many built-in families the generated table names */
int               builtinPresetFamilyCount();
/**
 * @brief The name of a built-in family.
 * @param family  0 .. builtinPresetFamilyCount()-1
 * @return        the name, or "" when out of range
 */
const char*       builtinPresetFamilyName(int family);

} // namespace ambient
