// Noctuary -- Z-plane filter, after the idea Dave Rossum built into the E-mu Morpheus
// (US 5,170,369, expired): four filter "frames" sit on the corners of a square, and a point
// (X, Y) inside it is a filter whose POLES AND ZEROS are interpolated between the corners.
// Move the point and the whole resonant structure glides, always through stable filters.
//
// The coefficient tables of the original are proprietary firmware data; this bank is our own,
// built in the same architecture: up to six cascaded two-pole/two-zero sections (a 12-pole
// filter, the order the Morpheus used), interpolation in the polar z-plane domain (log centre
// frequency, log bandwidth), never on the coefficients themselves. Every section is normalised
// to unity at its own peak, and the cascade is normalised again over the section frequencies,
// so a shape can be extremely resonant without becoming loud.
#pragma once
#include "Dsp.h"

namespace ambient {

constexpr int kZSections = 6;
// A hundred and fifty-five shapes, generated by Tools/make_zplane_bank.py, which is where the
// ratios and the acoustics behind each one are written down. The first sixteen are the original
// hand-written bank, carried over frequency for frequency: the library's presets name their shape
// as text ("z_shape=Glass"), so those names and their order are frozen. New shapes are appended.
constexpr int kZShapes     = 155;
constexpr int kZCategories = 12;
extern const char* const kZShapeNames[kZShapes];
extern const char* const kZCategoryNames[kZCategories];
// Which family a shape belongs to. Display only -- the parameter's numbering stays historical,
// and the editor sorts the list into families for the eye.
extern const unsigned char kZShapeCategory[kZShapes];
extern const char* const kZModeNames[4];   // Off, Series, Replace, Modal

// One two-pole / two-zero section. A zero frequency of 0 means "no zeros" (a plain resonator).
struct ZSection { float poleHz = 1000.0f, poleBw = 100.0f, zeroHz = 0.0f, zeroBw = 0.0f, gain = 1.0f; };
struct ZFrame   { ZSection s[kZSections]; int used = 0; };

// Corner descriptor: up to six centre frequencies plus the rules that shape them. Compact on
// purpose -- one readable line per corner instead of a wall of coefficients.
struct ZCornerSpec {
    float hz[kZSections];   // 0 ends the list
    float bwRatio;          // pole bandwidth as a fraction of the centre frequency (small = resonant)
    float zeroRatio;        // zero frequency / pole frequency (0 = no zeros; 1 = notch at the pole)
    float zeroBwRatio;      // zero bandwidth / zero frequency (small = deep notch)
    float tilt;             // gain factor per section, applied as tilt^i
};
// Eight corners of a cube: (0,0) (1,0) (0,1) (1,1) on the Transform = 0 face, then the same four
// on the Transform = 1 face. A cube, not a square, which is what the original is named after --
// and the near face is exactly the filter that was there before the third axis existed, so a
// preset that never mentions Transform (its default is 0) sounds as it always did.
extern const ZCornerSpec kZCorners[kZShapes][8];

ZFrame zFrameFromSpec(const ZCornerSpec& c);
// Trilinear interpolation of the eight corner frames in the log-frequency / log-bandwidth domain.
ZFrame zInterpolate(int shape, float x, float y, float z = 0.0f);

// ---------------------------------------------------------------- modal
//
// The same frames read as what they physically are. A cascade of biquads SHAPES a spectrum: it
// takes away what is not there and leaves what is. A parallel bank of two-pole resonators, one
// per mode, each with its own decay time, RINGS: hit it and it goes on sounding after the input
// has stopped, which is what a bar, a bell, a membrane or a room actually does. That is modal
// synthesis (Smith, Physical Audio Signal Processing; Bilbao, Numerical Sound Synthesis), and
// the bank already holds the data for it -- the mode ratios of struck and blown objects, taken
// from the acoustics literature. The cascade was using them as filter frequencies. This uses
// them as modes.
//
// Every resonator is normalised to unity gain at its own peak, so a steady tone at a mode's
// frequency comes out at the level it went in and the bank cannot run away however long the
// decay is set.
class ZModal {
public:
    void prepare(float sr) { sr_ = sr; reset(); }
    void reset();
    // `decaySeconds` is the T60 of the lowest mode; `damp` shortens the higher ones (0 = every
    // mode rings as long as the lowest, 1 = decay time inversely proportional to frequency,
    // which is roughly what a real object does).
    void set(const ZFrame& f, float decaySeconds, float damp);
    int  used() const { return used_; }
    inline float tick(int ch, float x)
    {
        float sum = 0.0f;
        for (int i = 0; i < used_; ++i) {
            Mode& m = modes_[i];
            const float y = m.b0 * x + m.a1 * m.z1[ch] + m.a2 * m.z2[ch];
            m.z2[ch] = m.z1[ch];
            m.z1[ch] = y;
            sum += y * m.gain;
        }
        return sum * norm_;
    }
    // See ZBiquad::guard: the same climb, over a bank whose poles sit even closer to the circle.
    inline bool guard()
    {
        bool hit = false;
        for (int i = 0; i < used_; ++i) {
            Mode& m = modes_[i];
            for (int ch = 0; ch < 2; ++ch)
                if (!(std::fabs(m.z1[ch]) < 1.0e9f && std::fabs(m.z2[ch]) < 1.0e9f)) {
                    m.z1[ch] = m.z2[ch] = 0.0f;
                    hit = true;
                }
        }
        return hit;
    }
    // |H(f)| of the whole bank, for the display: the modes add, they do not multiply.
    float magnitudeAt(float hz) const;

private:
    struct Mode {
        float b0 = 0.0f, a1 = 0.0f, a2 = 0.0f, gain = 1.0f, hz = 0.0f, r = 0.0f;
        float z1[2] = { 0.0f, 0.0f }, z2[2] = { 0.0f, 0.0f };
    };
    Mode  modes_[kZSections];
    int   used_ = 0;
    float norm_ = 1.0f;
    float sr_ = 48000.0f;
};



// A cascaded two-pole/two-zero section, transposed direct form II.
struct ZBiquad {
    float b0 = 1.0f, b1 = 0.0f, b2 = 0.0f, a1 = 0.0f, a2 = 0.0f;
    float z1 = 0.0f, z2 = 0.0f;
    // Poles and zeros from centre frequencies and bandwidths; the section is normalised to
    // unity gain at its own pole frequency, then scaled by `gain`.
    void set(const ZSection& s, float sr);
    // |H| at the given angular frequency (radians per sample), for the cascade normalisation.
    float magnitudeAt(float w) const;
    // |H|^2 from precomputed cos/sin of w and 2w (the normalisation grid).
    float magSqAt(float c1, float s1, float c2, float s2) const
    {
        const float nr = b0 + b1 * c1 + b2 * c2, ni = -(b1 * s1 + b2 * s2);
        const float dr = 1.0f + a1 * c1 + a2 * c2, di = -(a1 * s1 + a2 * s2);
        return (nr * nr + ni * ni) / std::max(dr * dr + di * di, 1e-20f);
    }
    inline float tick(float x)
    {
        const float y = b0 * x + z1;
        z1 = b1 * x - a1 * y + z2;
        z2 = b2 * x - a2 * y;
        return y;
    }
    // A resonant filter whose centre is swept while it is still ringing can take in more energy per
    // cycle than it lets out. Every coefficient here is clamped to a stable pole, and a fixed setting
    // is stable at any value -- sixty random ones were -- but sweeping one is not the same thing as
    // standing at either end of the sweep, and a Q of three hundred needs very little help. The state
    // then grows block by block until it is no longer a number, and from that moment the instrument
    // is silent until it is reloaded, because a NaN multiplied by anything stays a NaN.
    //
    // So the state is looked at once a block. The bound is far above anything music reaches and far
    // below where a float stops counting, which is the room needed to notice the climb before it
    // arrives at infinity. Below it this costs two comparisons a block and changes nothing.
        inline bool guard()
    {
        if (std::fabs(z1) < 1.0e9f && std::fabs(z2) < 1.0e9f) return false;   // false for a NaN too
        z1 = z2 = 0.0f;
        return true;
    }
    void copyCoefficients(const ZBiquad& o) { b0 = o.b0; b1 = o.b1; b2 = o.b2; a1 = o.a1; a2 = o.a2; }
    void reset() { z1 = z2 = 0.0f; }
};

// Builds the cascade of a frame into `ch` (f.used sections) and returns the gain that brings its
// loudest point back to unity. Every section is first normalised to its own maximum over a
// 16-point logarithmic grid -- normalising at the pole frequency alone fails for a section whose
// zero sits on its pole (a notch), and the cascade would then be either silent or very loud.
void zWarmTables();    // build the static tables off the audio thread (Engine::prepare)
void zWarmShapes();    // and the per-shape corner table
float zBuildCascade(const ZFrame& f, ZBiquad* ch, float sr);

// One two-pole resonator (constant-peak-gain form), used by the Air "Ghost" mode.
struct Resonator {
    float b0 = 0.0f, a1 = 0.0f, a2 = 0.0f;
    float s1 = 0.0f, s2 = 0.0f;
    void set(float hz, float bw, float gain, float sr)
    {
        const float f = clampv(hz, 20.0f, sr * 0.45f);
        const float r = std::exp(-kPi * clampv(bw, 1.0f, sr * 0.2f) / sr);
        const float th = kTwoPi * f / sr;
        a1 = -2.0f * r * std::cos(th);
        a2 = r * r;
        b0 = gain * (1.0f - r) * std::sqrt(std::max(1.0f - 2.0f * r * std::cos(2.0f * th) + r * r, 1e-6f));
    }
    inline float tick(float in)
    {
        const float y = b0 * in - a1 * s1 - a2 * s2;
        s2 = s1; s1 = y;
        return y;
    }
    // See ZBiquad::guard. The body's twelve modes are swept whenever its root moves.
    inline bool guard()
    {
        if (std::fabs(s1) < 1.0e9f && std::fabs(s2) < 1.0e9f) return false;
        s1 = s2 = 0.0f;
        return true;
    }
    void reset() { s1 = s2 = 0.0f; }
};

} // namespace ambient
