/**
 * @file ZPlane.h
 * @brief Z-plane filter, after the idea Dave Rossum built into the E-mu Morpheus
 *        (US 5,170,369, expired): four filter "frames" sit on the corners of a square, and a point
 *        (X, Y) inside it is a filter whose POLES AND ZEROS are interpolated between the corners.
 *
 * Move the point and the whole resonant structure glides, always through stable filters.
 *
 * The coefficient tables of the original are proprietary firmware data; this bank is our own,
 * built in the same architecture: up to six cascaded two-pole/two-zero sections (a 12-pole
 * filter, the order the Morpheus used), interpolation in the polar z-plane domain (log centre
 * frequency, log bandwidth), never on the coefficients themselves. Every section is normalised
 * to unity at its own peak, and the cascade is normalised again over the section frequencies,
 * so a shape can be extremely resonant without becoming loud.
 *
 * The voice (Voice.h) owns a pair of cascades and a modal bank; at control rate it interpolates
 * the frame for the shape's wandering point (zInterpolate), scales it by key tracking and
 * resonance, and either builds the cascade (zBuildCascade) or sets the modal bank (ZModal::set);
 * per sample it runs one or the other. The corner tables themselves are generated
 * (Core/src/ZPlaneBank.inc).
 */
#pragma once
#include "Dsp.h"

namespace ambient {

constexpr int kZSections = 6;   ///< sections in a frame: six two-pole/two-zero pairs, a 12-pole filter
/**
 * @brief A hundred and fifty-five shapes, generated by Tools/make_zplane_bank.py, which is where the
 *        ratios and the acoustics behind each one are written down.
 *
 * The first sixteen are the original
 * hand-written bank, carried over frequency for frequency: the library's presets name their shape
 * as text ("z_shape=Glass"), so those names and their order are frozen. New shapes are appended.
 */
constexpr int kZShapes     = 155;
constexpr int kZCategories = 12;   ///< the families the shapes are sorted into for the eye (kZCategoryNames)
extern const char* const kZShapeNames[kZShapes];         ///< the shapes' names, in the frozen order the presets store them by
extern const char* const kZCategoryNames[kZCategories];  ///< the families' names, indexed by kZShapeCategory
/**
 * @brief Which family a shape belongs to. Display only -- the parameter's numbering stays historical,
 *        and the editor sorts the list into families for the eye.
 */
extern const unsigned char kZShapeCategory[kZShapes];
extern const char* const kZModeNames[4];   ///< Off, Series, Replace, Modal

/** @brief One two-pole / two-zero section. A zero frequency of 0 means "no zeros" (a plain resonator). */
struct ZSection {
    float poleHz = 1000.0f,   ///< @brief pole centre frequency in Hz
    poleBw = 100.0f,          ///< @brief pole bandwidth in Hz (small = resonant)
    zeroHz = 0.0f,            ///< @brief zero centre frequency in Hz, 0 = no zeros
    zeroBw = 0.0f,            ///< @brief zero bandwidth in Hz
    gain = 1.0f;              ///< @brief the section's gain factor in the cascade (the corner's tilt^i)
};
/** @brief A filter frame: the sections in use, as one point of the cube evaluates to. */
struct ZFrame   {
    ZSection s[kZSections];   ///< @brief the sections; the first `used` are valid
    int used = 0;             ///< @brief how many sections this frame has (0 .. kZSections)
};

/**
 * @brief Corner descriptor: up to six centre frequencies plus the rules that shape them. Compact on
 *        purpose -- one readable line per corner instead of a wall of coefficients.
 */
struct ZCornerSpec {
    float hz[kZSections];   ///< 0 ends the list
    float bwRatio;          ///< pole bandwidth as a fraction of the centre frequency (small = resonant)
    float zeroRatio;        ///< zero frequency / pole frequency (0 = no zeros; 1 = notch at the pole)
    float zeroBwRatio;      ///< zero bandwidth / zero frequency (small = deep notch)
    float tilt;             ///< gain factor per section, applied as tilt^i
};
/**
 * @brief Eight corners of a cube: (0,0) (1,0) (0,1) (1,1) on the Transform = 0 face, then the same four
 *        on the Transform = 1 face.
 *
 * A cube, not a square, which is what the original is named after --
 * and the near face is exactly the filter that was there before the third axis existed, so a
 * preset that never mentions Transform (its default is 0) sounds as it always did.
 */
extern const ZCornerSpec kZCorners[kZShapes][8];

/**
 * @brief Expands a corner descriptor into a frame: one section per listed frequency, with the
 *        bandwidth, zero and gain the corner's ratios prescribe.
 *
 * The pole bandwidth is floored at 0.5 Hz; a zeroRatio of 0 gives sections without zeros; the
 * gain of section i is tilt^i. Pure arithmetic, but zInterpolate caches its results per shape so
 * this runs once per corner, not per voice.
 *
 * @param c  the corner
 * @return   the frame, `used` set to the number of frequencies before the first 0
 */
ZFrame zFrameFromSpec(const ZCornerSpec& c);
/**
 * @brief Trilinear interpolation of the eight corner frames in the log-frequency / log-bandwidth domain.
 *
 * Control rate, audio thread: the corners' logarithms are held per shape (built on first use, or
 * beforehand by zWarmShapes), so a call is eight weights over a few numbers per section. At z = 0
 * it is exactly the bilinear interpolation of the near face. A zero that exists in every corner is
 * interpolated; if any corner has none, the section has none.
 *
 * @param shape  0 .. kZShapes-1 (clamped)
 * @param x      the point's X, 0 .. 1 (clamped)
 * @param y      the point's Y, 0 .. 1 (clamped)
 * @param z      the point's Transform, 0 .. 1 (clamped); 0 is the filter as it was before the third axis
 * @return       the frame at that point, `used` the fewest sections of any corner
 */
ZFrame zInterpolate(int shape, float x, float y, float z = 0.0f);

// ---------------------------------------------------------------- modal
//
/**
 * @brief The same frames read as what they physically are.
 *
 * A cascade of biquads SHAPES a spectrum: it
 * takes away what is not there and leaves what is. A parallel bank of two-pole resonators, one
 * per mode, each with its own decay time, RINGS: hit it and it goes on sounding after the input
 * has stopped, which is what a bar, a bell, a membrane or a room actually does. That is modal
 * synthesis (Smith, Physical Audio Signal Processing; Bilbao, Numerical Sound Synthesis), and
 * the bank already holds the data for it -- the mode ratios of struck and blown objects, taken
 * from the acoustics literature. The cascade was using them as filter frequencies. This uses
 * them as modes.
 *
 * Every resonator is normalised to unity gain at its own peak, so a steady tone at a mode's
 * frequency comes out at the level it went in and the bank cannot run away however long the
 * decay is set.
 */
class ZModal {
public:
    /**
     * @brief Remembers the sample rate every mode's angle and radius are computed from, and clears the state.
     * @param sr  sample rate in Hz
     */
    void prepare(float sr) { sr_ = sr; reset(); }
    /** @brief Silences every mode on both channels; the coefficients stay. */
    void reset();
    /**
     * @brief Sets the bank from a frame: one mode per section, at the section's pole frequency.
     *
     * `decaySeconds` is the T60 of the lowest mode; `damp` shortens the higher ones (0 = every
     * mode rings as long as the lowest, 1 = decay time inversely proportional to frequency,
     * which is roughly what a real object does).
     *
     * Sections below 5 Hz or above 0.49 of the sample rate are skipped. Each mode gets unity gain
     * at its own frequency and the section's gain as its weight; the bank is normalised on the
     * expected power of the weights rather than on the sum of the peaks, so six modes and two come
     * out at the same level. Control rate, audio thread.
     *
     * @param f             the frame (from zInterpolate, scaled by the voice)
     * @param decaySeconds  T60 of the lowest mode, 0.02 .. 40 s (clamped)
     * @param damp          0 .. 1, how much shorter the high modes ring
     */
    void set(const ZFrame& f, float decaySeconds, float damp);
    /** @return how many modes are ringing after the last set() */
    int  used() const { return used_; }
    /**
     * @brief One sample of one channel through the bank: every mode is run and the outputs add.
     * @param ch  0 left, 1 right (each mode keeps a state per channel)
     * @param x   the input sample
     * @return    the sum of the modes, normalised
     */
    inline float tick(int ch, float x)
    {
        float sum = 0.0f;
        for (int i = 0; i < used_; ++i) {
            Mode& m = modes_[i];
            const float y = m.b0 * x + m.a1 * m.z1[ch] + m.a2 * m.z2[ch];
            m.z2[ch] = m.z1[ch];
            m.z1[ch] = y;
            sum += y * m.gain;
        }
        return sum * norm_;
    }
    /**
     * @brief See ZBiquad::guard: the same climb, over a bank whose poles sit even closer to the circle.
     * @return whether any mode's state had left the bound (or was not a number) and was reset
     */
    inline bool guard()
    {
        bool hit = false;
        for (int i = 0; i < used_; ++i) {
            Mode& m = modes_[i];
            for (int ch = 0; ch < 2; ++ch)
                if (!(std::fabs(m.z1[ch]) < 1.0e9f && std::fabs(m.z2[ch]) < 1.0e9f)) {
                    m.z1[ch] = m.z2[ch] = 0.0f;
                    hit = true;
                }
        }
        return hit;
    }
    /**
     * @brief |H(f)| of the whole bank, for the display: the modes add, they do not multiply.
     *
     * Sums the complex responses, phases included, and takes the magnitude of the sum.
     *
     * @param hz  the frequency to evaluate at, in Hz (clamped to 1 .. half the sample rate)
     * @return    the magnitude, normalised as tick() is
     */
    float magnitudeAt(float hz) const;

private:
    /** @brief One ringing mode: a two-pole resonator with a state per channel. */
    struct Mode {
        float b0 = 0.0f,     ///< @brief input gain for unity at the mode's own frequency
              a1 = 0.0f,     ///< @brief feedback coefficient 2 r cos(w)
              a2 = 0.0f,     ///< @brief feedback coefficient -r^2
              gain = 1.0f,   ///< @brief the section's weight in the sum
              hz = 0.0f,     ///< @brief the mode's frequency in Hz
              r = 0.0f;      ///< the pole radius, strictly inside the unit circle
        float z1[2] = { 0.0f, 0.0f },   ///< @brief the previous output, per channel
              z2[2] = { 0.0f, 0.0f };   ///< the output before that, per channel
    };
    Mode  modes_[kZSections];   ///< the bank
    int   used_ = 0;            ///< how many of modes_ ring
    float norm_ = 1.0f;         ///< 1 / sqrt of the summed squared weights: keeps the level even
    float sr_ = 48000.0f;       ///< the sample rate the modes were computed for (prepare)
};



/** @brief A cascaded two-pole/two-zero section, transposed direct form II. */
struct ZBiquad {
    float b0 = 1.0f,   ///< @brief feedforward: the input's weight
          b1 = 0.0f,   ///< @brief feedforward: one sample back
          b2 = 0.0f,   ///< @brief feedforward: two samples back
          a1 = 0.0f,   ///< @brief feedback: one sample back
          a2 = 0.0f;   ///< feedback: two samples back
    float z1 = 0.0f,   ///< @brief the first state variable
          z2 = 0.0f;   ///< the second state variable
    /**
     * @brief Poles and zeros from centre frequencies and bandwidths; the section is normalised to
     *        unity gain at its own pole frequency, then scaled by `gain`.
     *
     * The pole radius is capped at 0.99995 (about 0.4 s of ringing) so no interpolated point can
     * blow up; in practice the gain is applied by zBuildCascade, which normalises the section over
     * its whole grid, so this leaves b0 at 1.
     *
     * @param s   the section
     * @param sr  sample rate in Hz
     */
    void set(const ZSection& s, float sr);
    /**
     * @brief |H| at the given angular frequency (radians per sample), for the cascade normalisation.
     * @param w  the angular frequency, 0 .. pi
     * @return   the magnitude response there
     */
    float magnitudeAt(float w) const;
    /**
     * @brief |H|^2 from precomputed cos/sin of w and 2w (the normalisation grid).
     * @param c1  cos(w)
     * @param s1  sin(w)
     * @param c2  cos(2w)
     * @param s2  sin(2w)
     * @return    the squared magnitude response at w
     */
    float magSqAt(float c1, float s1, float c2, float s2) const
    {
        const float nr = b0 + b1 * c1 + b2 * c2, ni = -(b1 * s1 + b2 * s2);
        const float dr = 1.0f + a1 * c1 + a2 * c2, di = -(a1 * s1 + a2 * s2);
        return (nr * nr + ni * ni) / std::max(dr * dr + di * di, 1e-20f);
    }
    /**
     * @brief One sample through the section.
     * @param x  the input
     * @return   the output
     */
    inline float tick(float x)
    {
        const float y = b0 * x + z1;
        z1 = b1 * x - a1 * y + z2;
        z2 = b2 * x - a2 * y;
        return y;
    }
    /**
     * @brief Once a block, puts a state that has climbed out of all proportion back to zero.
     *
     * A resonant filter whose centre is swept while it is still ringing can take in more energy per
     * cycle than it lets out. Every coefficient here is clamped to a stable pole, and a fixed setting
     * is stable at any value -- sixty random ones were -- but sweeping one is not the same thing as
     * standing at either end of the sweep, and a Q of three hundred needs very little help. The state
     * then grows block by block until it is no longer a number, and from that moment the instrument
     * is silent until it is reloaded, because a NaN multiplied by anything stays a NaN.
     *
     * So the state is looked at once a block. The bound is far above anything music reaches and far
     * below where a float stops counting, which is the room needed to notice the climb before it
     * arrives at infinity. Below it this costs two comparisons a block and changes nothing.
     *
     * @return whether the state had left the bound (or was not a number) and was reset
     */
        inline bool guard()
    {
        if (std::fabs(z1) < 1.0e9f && std::fabs(z2) < 1.0e9f) return false;   // false for a NaN too
        z1 = z2 = 0.0f;
        return true;
    }
    /**
     * @brief Takes the coefficients of another section, keeping this one's state (the right channel copies the left's).
     * @param o  the section to copy from
     */
    void copyCoefficients(const ZBiquad& o) { b0 = o.b0; b1 = o.b1; b2 = o.b2; a1 = o.a1; a2 = o.a2; }
    /** @brief Clears the state; the coefficients stay. */
    void reset() { z1 = z2 = 0.0f; }
};

/**
 * @brief Builds the normalisation grid now, off the audio thread (Engine::prepare).
 *
 * build the static tables off the audio thread (Engine::prepare). Left alone, the first voice to
 * build a cascade would do it on the audio thread, inside the lock the language puts around a
 * function-local static.
 */
void zWarmTables();
/**
 * @brief and the per-shape corner table: builds the eight corners and their logarithms for every
 *        shape now, off the audio thread (Engine::prepare), so no voice does it under a lock.
 */
void zWarmShapes();
/**
 * @brief Builds the cascade of a frame into `ch` (f.used sections) and returns the gain that brings its
 *        loudest point back to unity.
 *
 * Every section is first normalised to its own maximum over a
 * 16-point logarithmic grid -- normalising at the pole frequency alone fails for a section whose
 * zero sits on its pole (a notch), and the cascade would then be either silent or very loud.
 *
 * The probe points are the fixed grid plus every pole and zero angle of the frame, so a needle-
 * sharp resonance is caught at its own peak. Each section is scaled to its geometric mean over the
 * points (a bell then keeps unity background and boosts only its peak), capped at 30 dB; the
 * product of the sections down each point gives the cascade's peak. Control rate, audio thread;
 * zWarmTables() must have run.
 *
 * @param f   the frame
 * @param ch  receives f.used sections' coefficients (their state is left alone)
 * @param sr  sample rate in Hz
 * @return    the make-up gain for the cascade's output, 1e-4 .. 16
 */
float zBuildCascade(const ZFrame& f, ZBiquad* ch, float sr);

/** @brief One two-pole resonator (constant-peak-gain form), used by the Air "Ghost" mode. */
struct Resonator {
    float b0 = 0.0f,   ///< @brief input gain, for a peak of `gain` whatever the bandwidth
          a1 = 0.0f,   ///< @brief feedback: one sample back
          a2 = 0.0f;   ///< feedback: two samples back
    float s1 = 0.0f,   ///< @brief the previous output
          s2 = 0.0f;   ///< the output before that
    /**
     * @brief Tunes the resonator.
     * @param hz    centre frequency in Hz (clamped to 20 .. 0.45 sr)
     * @param bw    bandwidth in Hz (clamped to 1 .. 0.2 sr); the pole radius is exp(-pi bw / sr)
     * @param gain  the peak gain
     * @param sr    sample rate in Hz
     */
    void set(float hz, float bw, float gain, float sr)
    {
        const float f = clampv(hz, 20.0f, sr * 0.45f);
        const float r = std::exp(-kPi * clampv(bw, 1.0f, sr * 0.2f) / sr);
        const float th = kTwoPi * f / sr;
        a1 = -2.0f * r * std::cos(th);
        a2 = r * r;
        b0 = gain * (1.0f - r) * std::sqrt(std::max(1.0f - 2.0f * r * std::cos(2.0f * th) + r * r, 1e-6f));
    }
    /**
     * @brief One sample through the resonator.
     * @param in  the input
     * @return    the output
     */
    inline float tick(float in)
    {
        const float y = b0 * in - a1 * s1 - a2 * s2;
        s2 = s1; s1 = y;
        return y;
    }
    /**
     * @brief See ZBiquad::guard. The body's twelve modes are swept whenever its root moves.
     * @return whether the state had left the bound (or was not a number) and was reset
     */
    inline bool guard()
    {
        if (std::fabs(s1) < 1.0e9f && std::fabs(s2) < 1.0e9f) return false;
        s1 = s2 = 0.0f;
        return true;
    }
    /** @brief Clears the state; the coefficients stay. */
    void reset() { s1 = s2 = 0.0f; }
};

} // namespace ambient
