"""Write Core/src/HarmonicEntropy.inc: the consonance of every interval of the octave, cent by cent,
as harmonic entropy (Erlich), for intervalConsonance() in Tuning.cpp (25.09.2026).

The review of the conductor against ambient harmony (finding F5) found intervalConsonance()
discontinuous: it looked for the simplest ratio within ten cents and scored its Tenney height, so
a 400-cent third, fourteen cents from 5/4, fell from 0.19 to 0.11 -- a tempered third was judged
as rough as a semitone, and the choice jumped between neighbouring ratios as Purity drifted.
Harmonic entropy is the standard continuous answer: hear the interval as a Gaussian of 17 cents
(about one per cent, the ear's resolution for a sustained dyad) spread over every ratio n/d with
n x d <= 10000, each weighted by 1 / sqrt(n d); the entropy of that distribution is low where one
simple ratio explains the interval and high where many compete. Mapped linearly onto the old
scale -- 1 for the unison, 0.05 at the most ambiguous interval -- it lands on the old values at
the just intervals within a few hundredths (the fifth 0.30 for 0.28, the fourth 0.21 for 0.22,
5/4 0.17 for 0.19, 16/15 0.11 for 0.12) and moves smoothly between them: the tempered major
third is 0.15. The width, the weight and the exponent of the mapping were fitted to the old
values at thirteen just intervals; sigma 17 and sqrt(n d) are also the literature's defaults.

The octave is the unison folded: intervalConsonance() folds every ratio into one octave, so the
top of the table joins the bottom -- within sixty cents under the octave the value is the larger
of the entropy there and the unison's shape mirrored.

    python Tools/make_harmonic_entropy.py
"""
import math
import os
from math import gcd

import numpy as np

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
OUT = os.path.join(ROOT, "Core", "src", "HarmonicEntropy.inc")
SIGMA = 17.0        # cents
LIMIT = 10000       # n x d
WEIGHT = 0.5        # exponent of 1 / (n d)
GAMMA = 1.0         # exponent of the mapping


def main():
    fr = [(1200.0 * math.log2(n / d), n * d)
          for d in range(1, 101) for n in range(d, 2 * d + 1)
          if n * d <= LIMIT and gcd(n, d) == 1]
    x = np.array([f[0] for f in fr])
    nd = np.array([f[1] for f in fr], dtype=float)
    # The octave's neighbours on both sides, so the ends of the table see what lies past them.
    x3 = np.concatenate([x, -x, 2400.0 - x])
    w3 = np.concatenate([nd, nd, nd]) ** (-WEIGHT)
    cents = np.arange(0, 1201, dtype=float)
    h = np.empty_like(cents)
    for i, c in enumerate(cents):
        p = w3 * np.exp(-(c - x3) ** 2 / (2.0 * SIGMA * SIGMA))
        p /= p.sum()
        p = p[p > 1e-15]
        h[i] = -(p * np.log(p)).sum()
    lo, hi = h.min(), h.max()
    cons = 0.05 + 0.95 * ((hi - h) / (hi - lo)) ** GAMMA
    for c in range(1141, 1201):   # the octave is the unison folded
        cons[c] = max(cons[c], cons[1200 - c])
    cons[1200] = cons[0]
    lines = ["// Generated by Tools/make_harmonic_entropy.py -- do not edit.",
             f"// Harmonic entropy (sigma {SIGMA:g} cents, n x d <= {LIMIT}, weights (n d)^-{WEIGHT:g}),",
             "// mapped onto 0.05 .. 1, one value per cent from the unison to the octave.",
             "static const float kHarmonicEntropy[1201] = {"]
    for i in range(0, 1201, 10):
        lines.append("    " + ", ".join(f"{v:.5f}f" for v in cons[i:i + 10]) + ",")
    lines.append("};")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    for c, name in ((0, "unison"), (112, "16/15"), (204, "9/8"), (316, "6/5"), (386, "5/4"), (400, "400 ct"),
                    (498, "4/3"), (702, "3/2"), (884, "5/3"), (969, "7/4")):
        print(f"{name:>7}: {cons[c]:.3f}")
    print("wrote", os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
