"""Noctuary -- the near layer's Auto table: which foreground a sound preset of a pack brings.

Rene's table (Tools/library/near_by_artist.json, 13.09.2026) says, per artist, what share of the
artist's presets get a foreground at all, which near presets they draw from and with what
weight, and how often the chosen one then speaks -- a class H (often), G (now and then) or S
(seldom) as a factor on the near preset's own Every. This turns it into Core/src/NearAuto.inc,
keyed by the PACK name (the artist's pack, from Tools/library/artists.py), because the
instrument knows packs and not artists.

    python Tools/make_near_auto.py
"""
import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
TABLE = os.path.join(HERE, "library", "near_by_artist.json")
OUT = os.path.join(ROOT, "Core", "src", "NearAuto.inc")


def artist_packs():
    sys.path.insert(0, os.path.join(HERE, "library"))   # artists.py imports its neighbours
    spec = importlib.util.spec_from_file_location("artists", os.path.join(HERE, "library", "artists.py"))
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return {a["inspiration"]: a["name"] for a in m.ARTISTS}


def near_names():
    names = []
    with open(os.path.join(ROOT, "Core", "src", "NearPresets.inc"), encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t.startswith('{ "'):
                names.append(t[3:t.index('"', 3)])
    return names


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    with open(TABLE, encoding="utf-8") as f:
        table = json.load(f)
    packs = artist_packs()
    known = set(near_names())
    entries, rows, missing, unknown = [], [], [], set()
    for artist, a in table["artists"].items():
        pack = packs.get(artist)
        if pack is None:
            missing.append(artist)
            continue
        first = len(entries)
        for p in a["presets"]:
            if p["preset"] not in known:
                unknown.add(p["preset"])
                continue
            lo, hi = p["rate_factor"]
            entries.append((p["preset"], float(p["weight"]), float(lo), float(hi)))
        rows.append((pack, float(a["share"]), first, len(entries) - first))
    if missing:
        print("no pack for: " + ", ".join(missing))
    if unknown:
        print("not in the near bank (skipped): " + ", ".join(sorted(unknown)))
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by Tools/make_near_auto.py from Tools/library/near_by_artist.json -- do not edit.\n")
        f.write("// %d packs, %d entries: the near preset, its weight within the pack, and the factor on its\n" % (len(rows), len(entries)))
        f.write("// Every (a range; H 0.6-1.0, G 1.0-2.0, S 2.0-4.0).\n")
        f.write("static const NearAutoEntry kNearAutoEntries[] = {\n")
        for name, w, lo, hi in entries:
            f.write("    { %s, %.4ff, %.2ff, %.2ff },\n" % (cstr(name), w, lo, hi))
        f.write("};\n")
        f.write("static const NearAutoPack kNearAutoPacks[] = {\n")
        for pack, share, first, count in rows:
            f.write("    { %s, %.2ff, %d, %d },\n" % (cstr(pack), share, first, count))
        f.write("};\n")
        f.write("static constexpr int kNumNearAutoPacks = %d;\n" % len(rows))
    print("wrote %s: %d packs, %d entries" % (OUT, len(rows), len(entries)))


if __name__ == "__main__":
    main()
